name: Release
on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: Release service.upnext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build zip files
        run: |
          sudo apt-get install xmlstarlet
          make multizip release=1
      - name: Get Leia filename
        id: get-leia-filename
        run: |
          echo "filename=$(cd ..;ls service.upnext*+leia.*.zip | head -1)" >> $GITHUB_OUTPUT
      - name: Get Matrix filename
        id: get-matrix-filename
        run: |
          echo "filename=$(cd ..;ls service.upnext*+matrix.*.zip | head -1)" >> $GITHUB_OUTPUT
      - name: Get details
        id: get-details
        run: |
          readarray -t details < <(sed -En '/^## Releases.*$/,/^[[:space:]]*$/!d;s/\r//g;s/^### (v[[:digit:]][^[:space:]]*.*)$/\1/p;s/^([[:space:]]*- .*)$/\1/p' changelog.txt)
          tag=`echo ${details[0]} | sed -En 's/(v[[:digit:]][^[:space:]]*).*/\1/p;'`
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "release_name=${details[0]}" >> $GITHUB_OUTPUT
          echo "body<<${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          for detail in "${details[@]:1}"; do
              echo "${detail}" >> $GITHUB_OUTPUT
          done
          echo "${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get-details.outputs.tag }} \
            ../${{ steps.get-matrix-filename.outputs.filename }} \
            ../${{ steps.get-leia-filename.outputs.filename }} \
            --title "${{ steps.get-details.outputs.release_name }}" \
            --notes "${{ steps.get-details.outputs.body }}" \
            --generate-notes \
            --draft
      # - name: Generate distribution zip and submit to official kodi repository
        # id: kodi-addon-submitter
        # uses: xbmc/action-kodi-addon-submitter@v1.2
        # with:
          # kodi-repository: repo-scripts
          # kodi-version: leia
          # addon-id: service.upnext
          # kodi-matrix: true
        # env:
          # GH_USERNAME: ${{secrets.GH_USERNAME}}
          # GH_TOKEN: ${{secrets.GH_TOKEN}}
          # EMAIL: ${{secrets.EMAIL}}
